project '03.CollectionViewPro.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
target '03.CollectionViewPro' do
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
    pod 'SnapKit'

end

